Repository relay-tools/relay-compiler-language-typescript, pull requests merged in 2019-10, with the labels that each got.

#140 Make relay variables writeable in ts
  src/TypeScriptGenerator.ts
  test/__snapshots__/TypeScriptGenerator-test.ts.snap
Labels: Version: Patch

#141 Add the ability to configure auto deploys
  scripts/deploy.sh
Labels: Version: Trivial

#143 Ensure CI can push to GitHub
  .travis.yml
  scripts/deploy.sh
Labels: Version: Patch

#144 Fix failing deployments by adding the proper git upstream
  scripts/deploy.sh
Labels: Version: Patch

#145 Fix deployment issue by pulling before setting upstream
  .travis.yml
  scripts/deploy.sh
Labels: Version: Patch

#146 Ensure on master, and that upstream is pointed at master
  .travis.yml
Labels: Version: Patch

#147 Correct version number [skip-ci]
  CHANGELOG.md
Labels: Version: Trivial

#148 Ensure tags are fetched for release
  .travis.yml
Labels: Version: Trivial

#155 Upgrade to relay v7
  example/package.json
  example/yarn.lock
  package.json
  src/TypeScriptGenerator.ts
  src/TypeScriptTypeTransformers.ts
  test/TypeScriptGenerator-test.ts
  test/__snapshots__/TypeScriptGenerator-test.ts.snap
  test/ambient.d.ts
  test/fixtures/generated-module/complete-example-no-cast.ts
  test/fixtures/type-generator-disabled/query-with-multiple-match-fields.graphql
  test/fixtures/type-generator/derived-field.graphql
  test/fixtures/type-generator/fragment-spread.graphql
  test/fixtures/type-generator/mutation-with-client-extension.graphql
  test/fixtures/type-generator/mutation-with-response-on-inline-fragments.graphql
  test/fixtures/type-generator/query-with-defer.graphql
  yarn.lock
Labels: Version: Major
