Repository relay-tools/relay-compiler-language-typescript, pull requests merged in 2021-04, with the labels that each got.

#309 feat: include .d.ts types in release
  package.json
  tsconfig.json
Labels: Version: Minor

#275 feat: drop typescript 3 support
  .github/workflows/ci.yml
  README.md
  package.json
  src/TypeScriptGenerator.ts
  src/TypeScriptTypeTransformers.ts
  src/addAnyTypeCast.ts
  test/fixtures/generated-module/complete-example-no-cast.ts
  test/fixtures/generated-module/complete-example.ts
  test/formatGeneratedModule-test.ts
  yarn.lock
Labels: Version: Major

#317 Revert "feat: drop typescript 3 and Node.js 10 support (#275)"
  .github/workflows/ci.yml
  README.md
  package.json
  src/TypeScriptGenerator.ts
  src/TypeScriptTypeTransformers.ts
  src/addAnyTypeCast.ts
  test/fixtures/generated-module/complete-example-no-cast.ts
  test/fixtures/generated-module/complete-example.ts
  test/formatGeneratedModule-test.ts
  yarn.lock
Labels: Version: Patch

#322 Remove artsy auto-config dep, update auto pinned version
  .autorc
  package.json
  scripts/deploy.sh
  yarn.lock
Labels: Version: Trivial

#318 feat: drop typescript 3 and Node.js 10 support (#275)
  .github/workflows/ci.yml
  README.md
  package.json
  src/TypeScriptGenerator.ts
  src/TypeScriptTypeTransformers.ts
  src/addAnyTypeCast.ts
  test/fixtures/generated-module/complete-example-no-cast.ts
  test/fixtures/generated-module/complete-example.ts
  test/formatGeneratedModule-test.ts
  yarn.lock
Labels: Version: Major
